"""Catálogo inicial (se carga en la hoja Catalogo la primera vez).
Generado desde Catalogo_Capacidad_Instalada.xlsx. Después se edita en el Sheet, no acá."""

# (Departamento, Tarea, Subtarea, Tipo, Orden, Activo)
CATALOGO_SEED = [
    ('SUELDOS', 'Liquidación de sueldos', 'Altas de empleados', 'Trabajo', 1, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Revisar acuerdos salariales', 'Trabajo', 2, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Papel de trabajo', 'Trabajo', 3, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Liquidación normal mensual', 'Trabajo', 4, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Liquidación normal quincenal', 'Trabajo', 5, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Liquidación SAC', 'Trabajo', 6, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Liquidación vacaciones', 'Trabajo', 7, "SI"),
    ('SUELDOS', 'Liquidación de sueldos', 'Liquidación final', 'Trabajo', 8, "SI"),
    ('SUELDOS', 'Cargas sociales', 'Liquidación', 'Trabajo', 9, "SI"),
    ('SUELDOS', 'Cargas sociales', 'Control', 'Trabajo', 10, "SI"),
    ('SUELDOS', 'Sindicato', 'Liquidación', 'Trabajo', 11, "SI"),
    ('SUELDOS', 'Sindicato', 'Control', 'Trabajo', 12, "SI"),
    ('SUELDOS', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 13, "SI"),
    ('SUELDOS', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 14, "SI"),
    ('SUELDOS', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 15, "SI"),
    ('SUELDOS', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 16, "SI"),
    ('SUELDOS', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 17, "SI"),
    ('SUELDOS', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 18, "SI"),
    ('SUELDOS', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 19, "SI"),
    ('SUELDOS', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 20, "SI"),
    ('SUELDOS', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 21, "SI"),
    ('GERENCIAL', 'Reuniones', 'Reunión de equipo (operativa)', 'Trabajo', 22, "SI"),
    ('GERENCIAL', 'Reuniones', 'Reunión de directorio', 'Trabajo', 23, "SI"),
    ('GERENCIAL', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 24, "SI"),
    ('GERENCIAL', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 25, "SI"),
    ('GERENCIAL', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 26, "SI"),
    ('GERENCIAL', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 27, "SI"),
    ('GERENCIAL', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 28, "SI"),
    ('TRÁMITES', 'Constituciones (SA-SRL)', 'Preparación de documentación', 'Trabajo', 29, "SI"),
    ('TRÁMITES', 'Constituciones (SA-SRL)', 'Presentación del trámite', 'Trabajo', 30, "SI"),
    ('TRÁMITES', 'Constituciones (SA-SRL)', 'Seguimiento y observaciones', 'Trabajo', 31, "SI"),
    ('TRÁMITES', 'Constituciones (SA-SRL)', 'Entrega al cliente', 'Trabajo', 32, "SI"),
    ('TRÁMITES', 'Cesión de cuotas', 'Preparación de documentación', 'Trabajo', 33, "SI"),
    ('TRÁMITES', 'Cesión de cuotas', 'Presentación del trámite', 'Trabajo', 34, "SI"),
    ('TRÁMITES', 'Cesión de cuotas', 'Seguimiento y observaciones', 'Trabajo', 35, "SI"),
    ('TRÁMITES', 'Cesión de cuotas', 'Entrega al cliente', 'Trabajo', 36, "SI"),
    ('TRÁMITES', 'Cambio de gerencia / renovación de autoridades', 'Preparación de documentación', 'Trabajo', 37, "SI"),
    ('TRÁMITES', 'Cambio de gerencia / renovación de autoridades', 'Presentación del trámite', 'Trabajo', 38, "SI"),
    ('TRÁMITES', 'Cambio de gerencia / renovación de autoridades', 'Seguimiento y observaciones', 'Trabajo', 39, "SI"),
    ('TRÁMITES', 'Cambio de gerencia / renovación de autoridades', 'Entrega al cliente', 'Trabajo', 40, "SI"),
    ('TRÁMITES', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 41, "SI"),
    ('TRÁMITES', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 42, "SI"),
    ('TRÁMITES', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 43, "SI"),
    ('TRÁMITES', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 44, "SI"),
    ('TRÁMITES', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 45, "SI"),
    ('TRÁMITES', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 46, "SI"),
    ('TRÁMITES', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 47, "SI"),
    ('TRÁMITES', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 48, "SI"),
    ('TRÁMITES', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 49, "SI"),
    ('IMPUESTOS', 'IVA mensual', 'Papel de trabajo', 'Trabajo', 50, "SI"),
    ('IMPUESTOS', 'IVA mensual', 'Liquidación', 'Trabajo', 51, "SI"),
    ('IMPUESTOS', 'IVA mensual', 'Control', 'Trabajo', 52, "SI"),
    ('IMPUESTOS', 'IIBB mensual', 'Papel de trabajo', 'Trabajo', 53, "SI"),
    ('IMPUESTOS', 'IIBB mensual', 'Liquidación', 'Trabajo', 54, "SI"),
    ('IMPUESTOS', 'IIBB mensual', 'Control', 'Trabajo', 55, "SI"),
    ('IMPUESTOS', 'Municipal', 'Seguridad e higiene', 'Trabajo', 56, "SI"),
    ('IMPUESTOS', 'Municipal', 'Publicidad y propaganda', 'Trabajo', 57, "SI"),
    ('IMPUESTOS', 'Municipal', 'Monotasa', 'Trabajo', 58, "SI"),
    ('IMPUESTOS', 'Monotributo', 'Control de facturación', 'Trabajo', 59, "SI"),
    ('IMPUESTOS', 'Monotributo', 'Recategorización', 'Trabajo', 60, "SI"),
    ('IMPUESTOS', 'VEPs', 'Autónomos', 'Trabajo', 61, "SI"),
    ('IMPUESTOS', 'VEPs', 'Monotributo', 'Trabajo', 62, "SI"),
    ('IMPUESTOS', 'VEPs', 'IVA diferido', 'Trabajo', 63, "SI"),
    ('IMPUESTOS', 'VEPs', 'Anticipo de ganancia', 'Trabajo', 64, "SI"),
    ('IMPUESTOS', 'VEPs', 'Bienes personales', 'Trabajo', 65, "SI"),
    ('IMPUESTOS', 'VEPs', 'Reliquidación', 'Trabajo', 66, "SI"),
    ('IMPUESTOS', 'Ganancias anual PH y PJ', 'Armado de planillas', 'Trabajo', 67, "SI"),
    ('IMPUESTOS', 'Ganancias anual PH y PJ', 'Pedido, reclamo y recepción de plan y control', 'Trabajo', 68, "SI"),
    ('IMPUESTOS', 'Ganancias anual PH y PJ', 'Hoja de trabajo', 'Trabajo', 69, "SI"),
    ('IMPUESTOS', 'Ganancias anual PH y PJ', 'Preliquidación', 'Trabajo', 70, "SI"),
    ('IMPUESTOS', 'Ganancias anual PH y PJ', 'Liquidación y presentación', 'Trabajo', 71, "SI"),
    ('IMPUESTOS', 'Bienes personales PH y PJ', 'Armado de planillas', 'Trabajo', 72, "SI"),
    ('IMPUESTOS', 'Bienes personales PH y PJ', 'Pedido, reclamo y recepción de plan y control', 'Trabajo', 73, "SI"),
    ('IMPUESTOS', 'Bienes personales PH y PJ', 'Hoja de trabajo', 'Trabajo', 74, "SI"),
    ('IMPUESTOS', 'Bienes personales PH y PJ', 'Preliquidación', 'Trabajo', 75, "SI"),
    ('IMPUESTOS', 'Bienes personales PH y PJ', 'Liquidación y presentación', 'Trabajo', 76, "SI"),
    ('IMPUESTOS', 'Planes de pagos', 'Confección', 'Trabajo', 77, "SI"),
    ('IMPUESTOS', 'Planes de pagos', 'Reliquidación', 'Trabajo', 78, "SI"),
    ('IMPUESTOS', 'Planes de pagos', 'Control', 'Trabajo', 79, "SI"),
    ('IMPUESTOS', 'Régimen informativo', 'BP – ACC y PART', 'Trabajo', 80, "SI"),
    ('IMPUESTOS', 'Régimen informativo', 'Participación societaria', 'Trabajo', 81, "SI"),
    ('IMPUESTOS', 'SIRADIG', 'Carga', 'Trabajo', 82, "SI"),
    ('IMPUESTOS', 'SIRADIG', 'Liquidación', 'Trabajo', 83, "SI"),
    ('IMPUESTOS', 'SIRADIG', 'Control', 'Trabajo', 84, "SI"),
    ('IMPUESTOS', 'MIPYME', 'Solicitud', 'Trabajo', 85, "SI"),
    ('IMPUESTOS', 'MIPYME', 'Renovación', 'Trabajo', 86, "SI"),
    ('IMPUESTOS', 'IIBB anual', 'Papel de trabajo', 'Trabajo', 87, "SI"),
    ('IMPUESTOS', 'IIBB anual', 'Cálculo de coeficiente', 'Trabajo', 88, "SI"),
    ('IMPUESTOS', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 89, "SI"),
    ('IMPUESTOS', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 90, "SI"),
    ('IMPUESTOS', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 91, "SI"),
    ('IMPUESTOS', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 92, "SI"),
    ('IMPUESTOS', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 93, "SI"),
    ('IMPUESTOS', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 94, "SI"),
    ('IMPUESTOS', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 95, "SI"),
    ('IMPUESTOS', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 96, "SI"),
    ('IMPUESTOS', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 97, "SI"),
    ('CONTABILIDAD', 'Contabilidad rutinaria', 'Conciliaciones', 'Trabajo', 98, "SI"),
    ('CONTABILIDAD', 'Contabilidad rutinaria', 'Asientos', 'Trabajo', 99, "SI"),
    ('CONTABILIDAD', 'Contabilidad rutinaria', 'Control de metodología', 'Trabajo', 100, "SI"),
    ('CONTABILIDAD', 'Contabilidad no rutinaria', 'Cuentas a cobrar y a pagar', 'Trabajo', 101, "SI"),
    ('CONTABILIDAD', 'Contabilidad no rutinaria', 'Resultado del ejercicio', 'Trabajo', 102, "SI"),
    ('CONTABILIDAD', 'Contabilidad no rutinaria', 'Asientos de cierre', 'Trabajo', 103, "SI"),
    ('CONTABILIDAD', 'Contabilidad no rutinaria', 'Certificación de balance', 'Trabajo', 104, "SI"),
    ('CONTABILIDAD', 'Contabilidad no rutinaria', 'Armado de planilla de balance', 'Trabajo', 105, "SI"),
    ('CONTABILIDAD', 'Actas', 'Confecciones', 'Trabajo', 106, "SI"),
    ('CONTABILIDAD', 'Actas', 'Traspaso de libros', 'Trabajo', 107, "SI"),
    ('CONTABILIDAD', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 108, "SI"),
    ('CONTABILIDAD', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 109, "SI"),
    ('CONTABILIDAD', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 110, "SI"),
    ('CONTABILIDAD', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 111, "SI"),
    ('CONTABILIDAD', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 112, "SI"),
    ('CONTABILIDAD', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 113, "SI"),
    ('CONTABILIDAD', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 114, "SI"),
    ('CONTABILIDAD', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 115, "SI"),
    ('CONTABILIDAD', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 116, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Honorarios', 'Reclamos de pagos', 'Trabajo', 117, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Honorarios', 'Confección de recibos', 'Trabajo', 118, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Honorarios', 'Actualización de honorarios en sistema', 'Trabajo', 119, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Confecciones HNR', 'Papel de trabajo', 'Trabajo', 120, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Confecciones HNR', 'Control', 'Trabajo', 121, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Recepción y clasificación de documentación', '', 'Trabajo', 122, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Comunicación con el cliente', 'WhatsApp', 'Trabajo', 123, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Comunicación con el cliente', 'Llamado telefónico', 'Trabajo', 124, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Comunicación con el cliente', 'Presencial', 'Trabajo', 125, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Rendición de fondo fijo', 'Papel de trabajo', 'Trabajo', 126, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 127, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 128, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 129, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 130, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 131, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 132, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 133, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 134, "SI"),
    ('ATENCIÓN AL CLIENTE', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 135, "SI"),
    ('RECURSOS HUMANOS', 'Selección del personal', 'Análisis de CV', 'Trabajo', 136, "SI"),
    ('RECURSOS HUMANOS', 'Selección del personal', 'Reuniones con postulantes', 'Trabajo', 137, "SI"),
    ('RECURSOS HUMANOS', 'Selección del personal', 'Evaluaciones', 'Trabajo', 138, "SI"),
    ('RECURSOS HUMANOS', 'Incorporación y acompañamiento', 'Proceso de ingreso', 'Trabajo', 139, "SI"),
    ('RECURSOS HUMANOS', 'Incorporación y acompañamiento', 'Capacitación y acompañamiento', 'Trabajo', 140, "SI"),
    ('RECURSOS HUMANOS', 'Administración del personal', 'Recibo de sueldo', 'Trabajo', 141, "SI"),
    ('RECURSOS HUMANOS', 'Administración del personal', 'Cuenta corriente', 'Trabajo', 142, "SI"),
    ('RECURSOS HUMANOS', 'Administración del personal', 'Pagos de sueldos', 'Trabajo', 143, "SI"),
    ('RECURSOS HUMANOS', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 144, "SI"),
    ('RECURSOS HUMANOS', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 145, "SI"),
    ('RECURSOS HUMANOS', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 146, "SI"),
    ('RECURSOS HUMANOS', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 147, "SI"),
    ('DOCUMENTACIÓN', 'Carga de documentación', 'Responsable inscripto', 'Trabajo', 148, "SI"),
    ('DOCUMENTACIÓN', 'Carga de documentación', 'Sociedades', 'Trabajo', 149, "SI"),
    ('DOCUMENTACIÓN', 'Carga de documentación', 'Monotributista', 'Trabajo', 150, "SI"),
    ('DOCUMENTACIÓN', 'Control de documentación', 'Responsable inscripto', 'Trabajo', 151, "SI"),
    ('DOCUMENTACIÓN', 'Control de documentación', 'Sociedades', 'Trabajo', 152, "SI"),
    ('DOCUMENTACIÓN', 'Control de documentación', 'Monotributista', 'Trabajo', 153, "SI"),
    ('DOCUMENTACIÓN', 'Solicitud y reclamo de documentación', 'Solicitud', 'Trabajo', 154, "SI"),
    ('DOCUMENTACIÓN', 'Solicitud y reclamo de documentación', 'Reclamo', 'Trabajo', 155, "SI"),
    ('DOCUMENTACIÓN', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 156, "SI"),
    ('DOCUMENTACIÓN', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 157, "SI"),
    ('DOCUMENTACIÓN', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 158, "SI"),
    ('DOCUMENTACIÓN', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 159, "SI"),
    ('DOCUMENTACIÓN', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 160, "SI"),
    ('DOCUMENTACIÓN', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 161, "SI"),
    ('DOCUMENTACIÓN', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 162, "SI"),
    ('DOCUMENTACIÓN', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 163, "SI"),
    ('DOCUMENTACIÓN', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 164, "SI"),
    ('COOPERATIVA', 'Caja', 'Registro de ingresos', 'Trabajo', 165, "SI"),
    ('COOPERATIVA', 'Caja', 'Registro de gastos', 'Trabajo', 166, "SI"),
    ('COOPERATIVA', 'Caja', 'Cierre de caja', 'Trabajo', 167, "SI"),
    ('COOPERATIVA', 'Gestión y mejoras del departamento', 'Capacitación', 'Disponible', 168, "SI"),
    ('COOPERATIVA', 'Gestión y mejoras del departamento', 'Informes', 'Disponible', 169, "SI"),
    ('COOPERATIVA', 'Gestión y mejoras del departamento', 'Planificación', 'Disponible', 170, "SI"),
    ('COOPERATIVA', 'Gestión y mejoras del departamento', 'Protocolos y procedimientos', 'Disponible', 171, "SI"),
    ('COOPERATIVA', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Monotributista', 'Trabajo', 172, "SI"),
    ('COOPERATIVA', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Responsable inscripto', 'Trabajo', 173, "SI"),
    ('COOPERATIVA', 'Tareas no rutinarias', 'Ingreso de cliente nuevo – Sociedad', 'Trabajo', 174, "SI"),
    ('COOPERATIVA', 'Tareas no rutinarias', 'Pedido especial de cliente', 'Trabajo', 175, "SI"),
    ('COOPERATIVA', 'Tareas no rutinarias', 'Otros imprevistos', 'Trabajo', 176, "SI"),
    ('GENERAL', 'Disponible', '', 'Disponible', 177, "SI"),
    ('GENERAL', 'Ausencias', 'Inasistencia (día personal)', 'Ausencia', 178, "SI"),
    ('GENERAL', 'Ausencias', 'Vacaciones', 'Ausencia', 179, "SI"),
]
